#!/usr/local/bin/python3

import os
import sys
import seqc
import configparser

# reading in configuration file
config_file = os.path.expanduser('~/.seqc/config')
config = configparser.ConfigParser()
if not config.read(config_file):
    raise ValueError('Please run ./configure (found in the seqc directory) before '
                     'attempting to run process_experiment.py.')

# obtaining rsa key from configuration file
rsa_key = config['key']['rsa_key_location']

# checking for instance status
inst_file = os.path.expanduser('~/.seqc/instance.txt')
try:
    # todo: deal with multiple instances launched simultaneously
    with open(inst_file, 'r') as f:
        inst_id = f.readline().strip('\n')
    s = seqc.remote.SSHServer(inst_id, rsa_key)
    s.connect()
    out, err = s.exec_command('less /data/seqc.log')
    if not out:
        raise FileNotFoundError('Error: SEQC log file not found in cluster. Something '
                                'went wrong with remote SEQC execution.')
    print('-'*50)
    print('Printing the contents of the remote SEQC log file:')
    print('-'*50)
    for line in out:
        print(line)
    print('-'*50)
except FileNotFoundError:
    print('You have not started a remote instance -- exiting.')
    sys.exit(0)
