#!/usr/local/bin/python3

import os
import seqc

# todo | get proper path here!!!
if os.path.isfile('/seqc/src/scripts/instance.txt'):
    with open('/seqc/src/scripts/instance.txt', 'r') as f:
        inst_id = f.readline().strip('\n')
    seqc.cluster_utils.terminate_cluster(inst_id)
else:
    pass
